#!/bin/sh

#Turn on Numlock
numlockx &

# Update Xresources
xrdb /home/tom/.config/X11/xresources

# Hotkeys 
sxhkd &

# Hide mousecursor when typing
xbanish &

# Keyboard Layout
setxkbmap -layout de

# Caps zu ESC
setxkbmap -option caps:escape

# Display Resolution
xrandr --output eDP-1 --mode 1920x1080 &

# Background
xwallpaper --focus ~/bilder/oneshot.png &

# Compositor
xcompmgr &

#Master Volume
pactl set-sink-volume 0 50%

# HDMI settings
xrandr --output HDMI-1 --set audio force-dvi

# Backlight
xbacklight -set 100

# WM
exec i3 
