#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#Turn on Numlock
numlockx &

xrdb /home/tom/.config/X11/xresources
sxhkd &

# Keyboard Layout
setxkbmap -layout de

# Caps zu ESC
setxkbmap -option caps:escape

# Background
xwallpaper --focus ~/bilder/oneshot.png &

# Display Resolution
xrandr --output eDP-1 --mode 1920x1080 &

# Compositor
xcompmgr &

#Master Volume
pactl set-sink-volume 0 50%

# HDMI settings
xrandr --output HDMI-1 --set audio force-dvi

# Backlight
light -S 100

# DWM
exec i3 
