#!/bin/sh

#Turn on Numlock
numlockx &

# Update Xresources
xrdb /home/tom/.config/X11/xresources

# Hotkeys 
sxhkd &

# Hide mousecursor when typing
xbanish -s -t 4000 -b &

# Notify daemon
dunst &

# Keyboard Layout
setxkbmap -layout de

# Caps zu ESC
setxkbmap -option caps:escape

# Display Resolution
xrandr --output eDP-1 --mode 1920x1080 &

# Background
xwallpaper --zoom ~/bilder/wallpaper.jpg &

#Master Volume
pactl set-sink-volume 0 50%

# HDMI settings
xrandr --output HDMI-1 --set audio force-dvi

# Backlight
xbacklight -set 100

# Compositor
xcompmgr &
#picom --config .config/picom/picom.sample.conf &

# WM
if [ "$(tty)" = "/dev/tty2" ]
	then
		exec i3
elif [ "$(tty)" = "/dev/tty1" ]
	then
		exec ~/.scripts/launch-dwm
fi
