#!/bin/bash

BAT=$(acpi | tail -1 | awk 'NR==1 gsub (/[%,]/,"") ;NR==1 {print $4}')
CHR=$(acpi | tail -1 | awk '{print $3}')

if [ "$CHR" != "Discharging," ]
	then
		status=$""
elif [ "$CHR" = '' ]
	then
		echo "?"
		exit
elif [ $BAT -lt 26 ]
    then
		status=$""
elif [ $BAT -lt 51 ]
    then
		status=$""
elif [ $BAT -lt 76 ]
    then
		status=$""

else
		status=$""
fi

echo "$status $BAT%"
