#!/bin/sh

cd ~/repos/dwm
git checkout master

for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	nolayout=$(echo $branch | sed 's/layout_//')
	if [ "$branch" != "master" ];then
		if [ "$branch" = "$nolayout" ]; then
			echo $branch
			git merge $branch -m $branch
		fi
	fi
done
