#!/bin/sh

trap 'update' 5

delim="|"

# update the bar
update()
{
	xsetroot -name	"$(status)"
	wait
	#echo -n $(status)
}

status()
{
		echo -n "$(~/.scripts/wireguard $delim) "
		echo -n "$(~/.scripts/network) "
		echo -n $delim
		echo -n "  $(df -h / | grep -E '/dev/sda2' | awk '{print $4}') "
		echo -n $delim
		echo -n "  $(xbacklight -get) % "
		echo -n $delim
		echo -n " $(~/.scripts/volume | head -1) "
		echo -n $delim
		echo -n " $(~/.scripts/battery) "
		echo -n $delim
		echo -n "  $(date '+%a %d. %b  %H:%M') "
}

while true; do
	update
	sleep 15 &
	wait $!
done

