#!/bin/sh

trap 'update_trap' 5

delim="⏐"

# update the bar
setroot()
{
	xsetroot -name "$(status)"
	wait
}

update_all()
{
	wireguard
	network
	volume
	battery

	setroot
}
update_trap()
{
	volume

	setroot
}

status()
{
	echo -n "$wireguard $delim "
	echo -n "$network "

	echo -n $delim
	echo -n "  $(df -h / | grep -E '/dev/sda2' | awk '{print $4}') "

	#echo -n $delim
	#echo -n " $delim  $(xbacklight -get) % "

	echo -n $delim
	echo -n " $volume "

	echo -n $delim
	echo -n " $battery "

	echo -n $delim
	echo -n "  $(date '+%a %d. %b  %H:%M') "
}

# update scripts
wireguard()
{
	wireguard="$(sh ~/.scripts/wireguard)"
}
network()
{
	network="$(sh ~/.scripts/network)"
}
volume()
{
	volume="$(sh ~/.scripts/volume | head -1)"
}
battery()
{
	battery="$(sh ~/.scripts/battery)"
}

while true; do
	update_all
	sleep 15 &
	wait $!
done
