#!/bin/sh

maxvol=150

max_volume()
{
		VOL=$(amixer get Master | grep -E -o '[0-9]{0,3}%' | grep -E -o '[0-9]{0,3}' | sort -u)
		[ $VOL -gt $maxvol ] && pactl set-sink-volume 0 "$maxvol"% && max_volume
}
volume()
{
		[ "$VOL" -le 65 ] && status="󰖀" || status="󰕾"
		[ "$VOL" -le 20 ] && status="󰕿"
		[ $mute ] && status="󰝟"
		echo "$status $VOL %"
}
# bar for notification
notify()
{
		for (( i=0; i<100; i+=10 ))
		do
				if [ $(( $i + 5 )) -eq $VOL ]
				then
						[ $mute ] && bar+="󰰱" || bar+="󱎖"
				elif [ $i -lt $VOL ]
				then
						[ $mute ] && bar+="󰰱" || bar+="󰄯"
				elif [ $i -ge $VOL ]
				then
						[ $mute ] && bar+=$"󰰲" || bar+=$"󰄰"
				fi
		done
		echo "$bar"
}

max_volume
mute=$(amixer get Master | grep -E -o '(\[off\])' | sort -u)

volume
notify
