#!/bin/bash
mode=$(echo -e "Laptop\nFernseher\nPapa" | dmenu -i -fn "System San Francisco Display")

intern=eDP-1
hdmi=HDMI-1
vga=DP-1

#Screen mode
if [ "$mode" = "" ]; then
		exit 1
elif [ "$mode" = "Laptop" ]; then
		xrandr --output "$intern" --mode 1920x1080
		xrandr --output "$hdmi" --off
		xrandr --output "$vga" --off
		xset s on
elif [ "$mode" = "Fernseher" ]; then
		xrandr --output "$intern" --off 
		xrandr --output "$hdmi" --mode 1360x768
		xrandr --output "$vga" --off
		xset s off
elif [ "$mode" = "Papa" ]; then
		xrandr --output "$intern" --off
		xrandr --output "$hdmi" --auto
		xrandr --output "$vga" --right-of "$hdmi" --auto
		xset s off
fi

xwallpaper --zoom ~/bilder/wallpaper.jpg
