#!/bin/bash
mode=$(echo -e "Laptop\nFernseher" | dmenu -i -fn "System San Francisco Display")

intern=eDP-1
hdmi=HDMI-1

#Screen mode
if [ "$mode" = "" ]; then
		exit 1
elif [ "$mode" = "Laptop" ]; then
		xrandr --output "$intern" --mode 1920x1080
		xrandr --output "$hdmi" --off
		xset s on
elif [ "$mode" = "Fernseher" ]; then
		xrandr --output "$intern" --off 
		xrandr --output "$hdmi" --mode 1360x768
		xset s off
fi

xwallpaper --zoom ~/bilder/wallpaper.jpg
